image: starcarr/libnx:latest

variables:
  PACKAGE_FOLDER: "pcsx_rearmed"

stages:
  - package

package:
  stage: package
  image: starcarr/libnx:latest
  script:
    - sh build.sh $PACKAGE_FOLDER master
  artifacts:
    name: $PACKAGE_FOLDER
    paths:
    - $PACKAGE_FOLDER
  only:
    - master

nightly:
  stage: package
  image: starcarr/libnx:nightly
  script:
    - sh build.sh $PACKAGE_FOLDER develop
  artifacts:
    name: $PACKAGE_FOLDER
    expire_in: 24 hours
    paths:
    - $PACKAGE_FOLDER
  except:
    - master
